/**
 * set-env.js — exécuté avant `ng build` sur Vercel
 *
 * Lit la variable d'environnement API_URL définie dans le dashboard Vercel
 * et l'injecte dans environment.prod.ts avant la compilation Angular.
 *
 * Variables Vercel à définir :
 *   API_URL  →  https://votre-backend.onrender.com/api
 */

const fs = require("fs");
const path = require("path");

const targetPath = path.join(
  __dirname,
  "src",
  "environments",
  "environment.prod.ts",
);

const isProduction = process.env["NODE_ENV"] === "production" || process.env["VERCEL"] === "1";
const apiUrl = process.env["API_URL"];

if (!apiUrl) {
  if (isProduction) {
    console.error("❌ ERROR: API_URL environment variable is not set!");
    console.error("   Set it in Vercel: Project > Settings > Environment Variables");
    process.exit(1);
  }
  // Local dev fallback only
  console.warn("⚠ API_URL not set, using local dev fallback: http://localhost:5292/api");
}

const resolvedApiUrl = apiUrl || "http://localhost:5292/api";

const content = `// Auto-generated by set-env.js — do not edit manually
export const environment = {
  production: true,
  apiUrl: '${resolvedApiUrl}'
};
`;

fs.writeFileSync(targetPath, content, { encoding: "utf8" });
console.log(`✔ environment.prod.ts generated with apiUrl = ${resolvedApiUrl}`);
